- name: Install Raspberry Pi packages
  hosts: raspberry_pi

  tasks:
  - name: Install eza repository
    block:
      - name: Create keyring directory
        become: true
        ansible.builtin.file:
          path: /etc/apt/keyrings
          state: directory
          mode: '0755'
      - name: Install eza apt key
        become: true
        ansible.builtin.get_url:
          url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
          dest: /etc/apt/keyrings/gierens.asc
          checksum: sha256:e29f5112e4d5553a49140bbdbcff23c6c3756cb451c15752bf8e9e7a9e0af1d2
          mode: '0644'
      - name: Install eza repo
        become: true
        ansible.builtin.apt_repository:
          repo: "deb [signed-by=/etc/apt/keyrings/gierens.asc] http://deb.gierens.de stable main"
          state: present
          filename: gierens
  - name: Install a list of packages
    become: true
    ansible.builtin.apt:
      pkg:
        - bat
        - cowsay
        - cowsay-off
        - curl
        - eza
        - fbterm
        - fd-find
        - fish
        - fonts-firacode
        - fortune-anarchism
        - fortune-mod
        - fortunes-bofh-excuses
        - fortunes-debian-hints
        - fortunes
        - fzf
        - gpg
        - htop
        - httpie
        - iperf3
        - lolcat
        - micro
        - most
        - ncdu
        - python3-virtualenv
        - ranger
        - ripgrep
        - rsync
        - screenfetch
        - sl
        - thefuck
        - tmux
        - tree
        - zoxide
      update_cache: yes
  - name: Install Starship
    become: true
    ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sh -s -- --yes

- name: Install Raspberry Pi 64 bits packages
  hosts: raspberry_pi_64

  tasks:
  - name: Install bottom
    become: true
    ansible.builtin.apt:
      deb: https://github.com/ClementTsang/bottom/releases/download/0.9.6/bottom_0.9.6_arm64.deb
  - name: Install fastfetch
    become: true
    ansible.builtin.apt:
      deb: https://github.com/fastfetch-cli/fastfetch/releases/download/2.11.0/fastfetch-linux-aarch64.deb

- name: Install Raspberry Pi 32 bits packages
  hosts: raspberry_pi_32

  tasks:
  - name: Install bottom
    become: true
    ansible.builtin.apt:
      deb: https://github.com/ClementTsang/bottom/releases/download/0.9.6/bottom_0.9.6_armhf.deb

- name: Configuration
  hosts: raspberry_pi

  tasks:
  - name: Copy micro syntax
    ansible.builtin.copy:
      src: config/micro/syntax/
      dest: '/home/{{ ansible_user }}/.config/micro/syntax/'
  - name: Copy micro settings with backup
    ansible.builtin.copy:
      src: config/micro/settings.json
      dest: '/home/{{ ansible_user }}/.config/micro/settings.json'
      backup: yes
  - name: Copy root micro syntax
    become: true
    ansible.builtin.copy:
      src: config/micro/syntax/
      dest: /root/.config/micro/syntax/
  - name: Copy root micro settings with backup
    become: true
    ansible.builtin.copy:
      src: config/micro/settings.json
      dest: /root/.config/micro/settings.json
      backup: yes
  - name: Copy fish functions
    ansible.builtin.copy:
      src: config/fish/functions/
      dest: '/home/{{ ansible_user }}/.config/fish/functions/'
  - name: Copy fish config
    ansible.builtin.blockinfile:
      path: '/home/{{ ansible_user }}/.config/fish/config.fish'
      append_newline: true
      backup: yes
      create: true
      marker: "# {mark} CONFIG ANSIBLE MANAGED BLOCK"
      block: |
        if status is-interactive
            set -gx MICRO_TRUECOLOR 1
            set -gx FZF_DEFAULT_COMMAND "fd --type file --color=always"
            set -gx FZF_DEFAULT_OPTS "--ansi"
            set -gx FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"
            set -gx EDITOR /usr/bin/micro
            set -gx PAGER /usr/bin/most
            set -gx MOST_EDITOR "micro +%d:1 %s"
            set -gx SLANG_EDITOR "micro +%d:1 %s"

            zoxide init fish | source
            starship init fish | source
        end
  - name: Install fisher
    ansible.builtin.shell: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
    args:
      executable: /usr/bin/fish
  - name: Install fisher packages
    ansible.builtin.shell: fisher install PatrickF1/fzf.fish
    args:
      executable: /usr/bin/fish
  - name: Change shell to fish
    become: true
    ansible.builtin.user:
      name: '{{ ansible_user }}'
      shell: /usr/bin/fish
