- name: Install Pi-hole
  hosts: pi_hole

  tasks:
  - name: Install Pi-hole executable
    become: true
    ansible.builtin.shell: curl -sSL https://install.pi-hole.net | bash /dev/stdin --unattended
    args:
      creates: /usr/local/bin/pihole

#- name: Install Caddy
#  hosts: pi_hole
#
#  tasks:
#  - name: Install Caddy executable   
