- name: Install Raspberry Pi packages
  hosts: raspberry_pi

  tasks:
  - name: Install a list of packages
    become: true
    ansible.builtin.apt:
      pkg:
        - bat
        - btm
        - cowsay
        - cowsay-off
        - curl
        - eza
        - fastfetch
        - fbterm
        - fd-find
        - fish
        - fonts-firacode
        - fortune-anarchism
        - fortune-mod
        - fortunes-bofh-excuses
        - fortunes-debian-hints
        - fortunes
        - fzf
        - gpg
        - htop
        - httpie
        - iperf3
        - lolcat
        - micro
        - most
        - ncdu
        - python3-virtualenv
        - ranger
        - ripgrep
        - rsync
        - screenfetch
        - sl
        - starship
        - thefuck
        - tmux
        - tree
        - zoxide
      update_cache: yes

- name: Configuration
  hosts: raspberry_pi

  tasks:
  - name: Copy micro syntax
    ansible.builtin.copy:
      src: config/micro/syntax/
      dest: '/home/{{ ansible_user }}/.config/micro/syntax/'
  - name: Copy micro settings with backup
    ansible.builtin.copy:
      src: config/micro/settings.json
      dest: '/home/{{ ansible_user }}/.config/micro/settings.json'
      backup: yes
  - name: Copy root micro syntax
    become: true
    ansible.builtin.copy:
      src: config/micro/syntax/
      dest: /root/.config/micro/syntax/
  - name: Copy root micro settings with backup
    become: true
    ansible.builtin.copy:
      src: config/micro/settings.json
      dest: /root/.config/micro/settings.json
      backup: yes
  - name: Copy fish functions
    ansible.builtin.copy:
      src: config/fish/functions/
      dest: '/home/{{ ansible_user }}/.config/fish/functions/'
  - name: Copy fish config
    ansible.builtin.blockinfile:
      path: '/home/{{ ansible_user }}/.config/fish/config.fish'
      append_newline: true
      backup: yes
      create: true
      marker: "# {mark} CONFIG ANSIBLE MANAGED BLOCK"
      block: |
        if status is-interactive
            set -gx MICRO_TRUECOLOR 1
            set -gx FZF_DEFAULT_COMMAND "fd --type file --color=always"
            set -gx FZF_DEFAULT_OPTS "--ansi"
            set -gx FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"
            set -gx EDITOR /usr/bin/micro
            set -gx PAGER /usr/bin/most
            set -gx MOST_EDITOR "micro +%d:1 %s"
            set -gx SLANG_EDITOR "micro +%d:1 %s"

            zoxide init fish | source
            starship init fish | source
        end
  - name: Install fisher
    ansible.builtin.shell: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
    args:
      executable: /usr/bin/fish
  - name: Install fisher packages
    ansible.builtin.shell: fisher install PatrickF1/fzf.fish
    args:
      executable: /usr/bin/fish
  - name: Change shell to fish
    become: true
    ansible.builtin.user:
      name: '{{ ansible_user }}'
      shell: /usr/bin/fish
