- name: Upgrade Raspberry Pis
  hosts: 
  - raspberry_pi
  - fan_controller

  tasks:
  - name: Upgrade all packages to their latest version, remove dependencies that are no longer required
    become: true
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
      autoremove: yes

- name: Upgrade Fisher packages
  hosts: 
  - raspberry_pi
  - container_hosts

  tasks:
  - name: Upgrade all fisher packages
    ansible.builtin.shell: fisher update
    args:
      executable: /usr/bin/fish

- name: Update Container Hosts
  hosts: container_hosts

  tasks:
  - name: Upgrade the rpm-ostree image without options, accept all defaults
    become: true
    ansible.posix.rpm_ostree_upgrade:
  - name: Unconditionally reboot the machine with all defaults
    become: true
    ansible.builtin.reboot:
    
- name: Update Pi-hole
  hosts: pi_hole

  tasks:
  - name: Upgrade Pi-hole executable
    ansible.builtin.shell: pihole -up

- name: Update Fan COntroller
  hosts: fan_controller

  tasks:
  - name: Clone Fan Controller repo
    ansible.builtin.git:
      repo: 'https://github.com/guillaumetousignant/fan_controller.git'
      dest: /home/pi/Code/fan_controller
